pipeline {
    agent any
    
    stages {
        stage('checkout') {
            steps {
                script {
                    git(
                        branch: '*/master',
                        credentialsId: 'f02ca424-2475-4f08-b66c-22db9e5a37cc',
                        url: 'https://github.com/bashashaikgit/simple-java-maven-app.git'
                    )
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
