pipeline {
    agent any

   
    stages {
        stage('checkout') {
            steps {
                script {
                    git(
                        branch: 'master',
                        credentialsId: 'github',
                        url: 'https://github.com/bashashaikgit/simple-java-maven-app.git'
                    )
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarCloud') {
                    sh "mvn sonar:sonar -Dsonar.organization='testorganization1293'"
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
